// src/data/products.js
export const Products = [
    { id: 71, name: "Accu-Chek Guide", salt: "Glucometer with Strips", category: "Diagnostic Tools", price: 950, mrp: 1250, discount: 24, imageUrl: "/productImage/Diagnostic_Tools.png", brandName: "Accu-Chek" },
    { id: 62, name: "Adrenaline Inj", salt: "Epinephrine IP", category: "Emergency Meds", price: 420, mrp: 500, discount: 16, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Adrenaline Inj" },
    { id: 82, name: "Allegra 120", salt: "Fexofenadine", category: "Generic Drugs", price: 180, mrp: 210, discount: 14, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Allegra" },
    { id: 33, name: "Amaryl 1mg", salt: "Glimepiride", category: "Diabetes Care", price: 65, mrp: 80, discount: 18, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Amaryl" },
    { id: 39, name: "Amiodarone 200", salt: "Amiodarone Hydrochloride", category: "Life Saving Medicines", price: 180, mrp: 230, discount: 21, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Amiodarone" },
    { id: 22, name: "Amlokind AT", salt: "Amlodipine & Atenolol", category: "Cardiac Care", price: 42, mrp: 49, discount: 14, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Amlokind" },
    { id: 52, name: "Arimidex 1mg", salt: "Anastrozole", category: "Oncology Drugs", price: 950, mrp: 1200, discount: 20, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Arimidex" },
    { id: 98, name: "Ascoril LS", salt: "Ambroxol & Levosalbutamol", category: "Generic Drugs", price: 105, mrp: 130, discount: 19, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Ascoril" },
    { id: 61, name: "Asthalin Nebuliser", salt: "Salbutamol Respirator", category: "Emergency Meds", price: 110, mrp: 140, discount: 21, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Asthalin" },
    { id: 20, name: "Atorva 10", salt: "Atorvastatin Calcium", category: "Cardiac Care", price: 68, mrp: 85, discount: 20, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Atorva" },
    { id: 63, name: "Atropine Inj", salt: "Atropine Sulphate", category: "Emergency Meds", price: 310, mrp: 380, discount: 18, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Atropine Inj" },
    { id: 10, name: "Augmentin 625 Duo", salt: "Amoxicillin & Potassium Clavulanate", category: "Antibiotics", price: 182, mrp: 210, discount: 13, imageUrl: "/productImage/Antibiotics.png", brandName: "Augmentin" },
    { id: 45, name: "Augmentin Duo Syr", salt: "Amoxycillin & Clavulanic Acid", category: "Pediatric Care", price: 135, mrp: 160, discount: 15, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Augmentin Duo Syr" },
    { id: 64, name: "Avil 25", salt: "Pheniramine Maleate", category: "Emergency Meds", price: 12, mrp: 18, discount: 33, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Avil" },
    { id: 12, name: "Azithral 500", salt: "Azithromycin", category: "Antibiotics", price: 68, mrp: 82, discount: 17, imageUrl: "/productImage/Antibiotics.png", brandName: "Azithral" },
    { id: 67, name: "B-D Scalpel 11", salt: "Surgical Steel Blade", category: "Surgical Equipment", price: 450, mrp: 600, discount: 25, imageUrl: "/productImage/Surgical_Equipment.png", brandName: "B-D Scalpel" },
    { id: 4, name: "Becosules Z", salt: "B-Complex with Vitamin C", category: "Generic Drugs", price: 35, mrp: 45, discount: 22, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Becosules" },
    { id: 92, name: "Betadine Soln", salt: "Povidone-Iodine", category: "Generic Drugs", price: 95, mrp: 120, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Betadine Soln" },
    { id: 44, name: "Calpol Syrup", salt: "Paracetamol Pediatric", category: "Pediatric Care", price: 45, mrp: 55, discount: 18, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Calpol" },
    { id: 18, name: "Cefakind 500", salt: "Cefuroxime Axetil", category: "Antibiotics", price: 450, mrp: 520, discount: 13, imageUrl: "/productImage/Antibiotics.png", brandName: "Cefakind" },
    { id: 13, name: "Ciplox 500", salt: "Ciprofloxacin", category: "Antibiotics", price: 42, mrp: 55, discount: 23, imageUrl: "/productImage/Antibiotics.png", brandName: "Ciplox" },
    { id: 27, name: "Clopitab 75", salt: "Clopidogrel", category: "Cardiac Care", price: 92, mrp: 110, discount: 16, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Clopitab" },
    { id: 9, name: "Combiflam", salt: "Ibuprofen & Paracetamol", category: "Generic Drugs", price: 42, mrp: 52, discount: 19, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Combiflam" },
    { id: 23, name: "Concor 5", salt: "Bisoprolol Fumarate", category: "Cardiac Care", price: 120, mrp: 145, discount: 17, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Concor" },
    { id: 94, name: "Cremaffin", salt: "Liquid Paraffin & Milk of Magnesia", category: "Generic Drugs", price: 210, mrp: 255, discount: 17, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Cremaffin" },
    { id: 2, name: "Crocin Advance", salt: "Paracetamol", category: "Generic Drugs", price: 15, mrp: 20, discount: 25, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Crocin Advance" },
    { id: 43, name: "Crocin Drops", salt: "Paracetamol Drops", category: "Pediatric Care", price: 35, mrp: 42, discount: 16, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Crocin" },
    { id: 35, name: "Dapalin 10", salt: "Dapagliflozin", category: "Diabetes Care", price: 160, mrp: 195, discount: 17, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Dapalin" },
    { id: 96, name: "Deriphyllin", salt: "Etophylline & Theophylline", category: "Cardiac Care", price: 45, mrp: 55, discount: 18, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Deriphyllin" },
    { id: 75, name: "Dettol Liquid 500ml", salt: "Antiseptic Disinfectant", category: "Personal Care", price: 165, mrp: 198, discount: 16, imageUrl: "/productImage/Personal_Care.png", brandName: "Dettol Liquid" },
    { id: 56, name: "Dexona Inj", salt: "Dexamethasone Sodium Phosphate", category: "Emergency Meds", price: 15, mrp: 22, discount: 31, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Dexona" },
    { id: 88, name: "Digene Gel", salt: "Antacid & Antigas", category: "Generic Drugs", price: 145, mrp: 170, discount: 14, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Digene Gel" },
    { id: 65, name: "Dispovan Syringe 5ml", salt: "Hypodermic Needle", category: "Surgical Equipment", price: 8, mrp: 12, discount: 33, imageUrl: "/productImage/Surgical_Equipment.png", brandName: "Dispovan Syringe" },
    { id: 1, name: "Dolo 650", salt: "Paracetamol IP", category: "Generic Drugs", price: 25, mrp: 32, discount: 21, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Dolo 650" },
    { id: 47, name: "Domstal Drops", salt: "Domperidone", category: "Pediatric Care", price: 35, mrp: 45, discount: 22, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Domstal Drops" },
    { id: 72, name: "Dr. Trust Oximeter", salt: "Pulse Oximetry Device", category: "Diagnostic Tools", price: 650, mrp: 999, discount: 35, imageUrl: "/productImage/Diagnostic_Tools.png", brandName: "Dr. Trust" },
    { id: 95, name: "Dulcoflex", salt: "Bisacodyl", category: "Generic Drugs", price: 10, mrp: 15, discount: 33, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Dulcoflex" },
    { id: 26, name: "Ecosprin 75", salt: "Aspirin", category: "Cardiac Care", price: 5, mrp: 8, discount: 37, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Ecosprin" },
    { id: 86, name: "Enterogermina", salt: "Bacillus Clausii", category: "Generic Drugs", price: 480, mrp: 550, discount: 12, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Enterogermina" },
    { id: 5, name: "Evion 400", salt: "Vitamin E", category: "Generic Drugs", price: 32, mrp: 40, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Evion" },
    { id: 53, name: "Femara 2.5", salt: "Letrozole", category: "Oncology Drugs", price: 680, mrp: 800, discount: 15, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Femara" },
    { id: 90, name: "Foracort 200", salt: "Budesonide & Formoterol", category: "Emergency Meds", price: 420, mrp: 510, discount: 17, imageUrl: "/productImage/Emergency_Meds.png", brandName: "Foracort" },
    { id: 30, name: "Galvus 50", salt: "Vildagliptin IP", category: "Diabetes Care", price: 255, mrp: 300, discount: 15, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Galvus" },
    { id: 28, name: "Glycomet GP 1", salt: "Glimepiride & Metformin", category: "Diabetes Care", price: 58, mrp: 70, discount: 17, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Glycomet GP" },
    { id: 89, name: "Glynase XL 5", salt: "Glipizide", category: "Diabetes Care", price: 45, mrp: 58, discount: 22, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Glynase" },
    { id: 16, name: "Gudcef 200", salt: "Cefpodoxime Proxetil", category: "Antibiotics", price: 155, mrp: 180, discount: 13, imageUrl: "/productImage/Antibiotics.png", brandName: "Gudcef" },
    { id: 37, name: "Heparin Sodium Inj", salt: "Heparin", category: "Life Saving Medicines", price: 550, mrp: 680, discount: 19, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Heparin Sodium Inj" },
    { id: 77, name: "Himalaya Face Wash", salt: "Neem & Turmeric", category: "Personal Care", price: 140, mrp: 175, discount: 20, imageUrl: "/productImage/Personal_Care.png", brandName: "Himalaya Face Wash" },
    { id: 29, name: "Januvia 100", salt: "Sitagliptin Phosphate", category: "Diabetes Care", price: 340, mrp: 400, discount: 15, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Januvia" },
    { id: 68, name: "Johnson Surgical Tape", salt: "Micropore Medical Tape", category: "Surgical Equipment", price: 85, mrp: 110, discount: 22, imageUrl: "/productImage/Surgical_Equipment.png", brandName: "Johnson Surgical Tape" },
    { id: 40, name: "Lanoxin 0.25", salt: "Digoxin IP", category: "Life Saving Medicines", price: 62, mrp: 75, discount: 17, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Lanoxin" },
    { id: 41, name: "Lasilix 40", salt: "Furosemide", category: "Life Saving Medicines", price: 12, mrp: 18, discount: 33, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Lasilix" },
    { id: 3, name: "Limcee", salt: "Vitamin C (Ascorbic Acid)", category: "Generic Drugs", price: 22, mrp: 28, discount: 21, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Limcee" },
    { id: 73, name: "Littmann Stethoscope", salt: "Classic III Edition", category: "Diagnostic Tools", price: 8500, mrp: 10500, discount: 19, imageUrl: "/productImage/Diagnostic_Tools.png", brandName: "Littmann Stethoscope" },
    { id: 87, name: "Liv 52", salt: "Hepatoprotective Herbal", category: "Generic Drugs", price: 125, mrp: 150, discount: 16, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Liv 52" },
    { id: 49, name: "Maxtra Syrup", salt: "Phenylephrine & Chlorpheniramine", category: "Pediatric Care", price: 78, mrp: 95, discount: 17, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Maxtra Syrup" },
    { id: 84, name: "Meftal Spas", salt: "Mefenamic Acid & Dicyclomine", category: "Generic Drugs", price: 48, mrp: 60, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Meftal Spas" },
    { id: 54, name: "Methofast 5mg", salt: "Methotrexate", category: "Oncology Drugs", price: 190, mrp: 240, discount: 20, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Methofast" },
    { id: 24, name: "Metosartan 50", salt: "Metoprolol Succinate", category: "Cardiac Care", price: 95, mrp: 115, discount: 17, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Metosartan" },
    { id: 17, name: "Mox 500", salt: "Amoxycillin", category: "Antibiotics", price: 85, mrp: 105, discount: 19, imageUrl: "/productImage/Antibiotics.png", brandName: "Mox 500" },
    { id: 69, name: "N95 Surgical Mask", salt: "5-Ply Protection", category: "Surgical Equipment", price: 45, mrp: 99, discount: 54, imageUrl: "/productImage/Surgical_Equipment.png", brandName: "N95 Surgical Mask" },
    { id: 36, name: "Nitrocontin 2.6", salt: "Nitroglycerin", category: "Life Saving Medicines", price: 215, mrp: 260, discount: 17, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Nitrocontin" },
    { id: 50, name: "Nolvadex 20", salt: "Tamoxifen Citrate", category: "Oncology Drugs", price: 120, mrp: 150, discount: 20, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Nolvadex" },
    { id: 42, name: "Norepin 4mg", salt: "Norepinephrine", category: "Life Saving Medicines", price: 850, mrp: 1100, discount: 22, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Norepin 4mg" },
    { id: 15, name: "OFLOX 200", salt: "Ofloxacin", category: "Antibiotics", price: 58, mrp: 72, discount: 19, imageUrl: "/productImage/Antibiotics.png", brandName: "OFLOX" },
    { id: 70, name: "Omron BP Monitor", salt: "HEM-7120 Digital", category: "Diagnostic Tools", price: 1950, mrp: 2400, discount: 18, imageUrl: "/productImage/Diagnostic_Tools.png", brandName: "Omron" },
    { id: 48, name: "Ondem Syrup", salt: "Ondansetron Hydrochloride", category: "Pediatric Care", price: 65, mrp: 80, discount: 18, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Ondem Syrup" },
    { id: 91, name: "Otrivin Nasal Spray", salt: "Xylometazoline", category: "Generic Drugs", price: 85, mrp: 105, discount: 19, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Otrivin" },
    { id: 80, name: "Pan 40", salt: "Pantoprazole", category: "Generic Drugs", price: 120, mrp: 145, discount: 17, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Pan 40" },
    { id: 25, name: "Ramistar 5", salt: "Ramipril", category: "Cardiac Care", price: 88, mrp: 105, discount: 16, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Ramistar" },
    { id: 81, name: "Rantac 150", salt: "Ranitidine Hydrochloride", category: "Generic Drugs", price: 35, mrp: 48, discount: 27, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Rantac" },
    { id: 66, name: "Romsons Foley Cath", salt: "Latex Urinary Catheter", category: "Surgical Equipment", price: 140, mrp: 180, discount: 22, imageUrl: "/productImage/Surgical_Equipment.png", brandName: "Romsonsoley Cath" },
    { id: 74, name: "Rossmax Thermometer", salt: "Digital Flexi-Tip", category: "Diagnostic Tools", price: 180, mrp: 250, discount: 28, imageUrl: "/productImage/Diagnostic_Tools.png", brandName: "Rossmax Thermometer" },
    { id: 21, name: "Rosuvas 10", salt: "Rosuvastatin Calcium", category: "Cardiac Care", price: 145, mrp: 175, discount: 17, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Rosuvas" },
    { id: 8, name: "Saridon", salt: "Propyphenazone, Paracetamol", category: "Generic Drugs", price: 38, mrp: 48, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Saridon" },
    { id: 76, name: "Savlon Soap", salt: "Antiseptic Soap Bar", category: "Personal Care", price: 55, mrp: 70, discount: 21, imageUrl: "/productImage/Personal_Care.png", brandName: "Savlon Soap" },
    { id: 78, name: "Sebamed Baby Wash", salt: "Gentle Cleaning Formula", category: "Personal Care", price: 420, mrp: 500, discount: 16, imageUrl: "/productImage/Personal_Care.png", brandName: "Sebamed Baby Wash" },
    { id: 79, name: "Sensodyne Toothpaste", salt: "Potassium Nitrate Relief", category: "Personal Care", price: 185, mrp: 215, discount: 13, imageUrl: "/productImage/Personal_Care.png", brandName: "Sensodyne Toothpaste" },
    { id: 99, name: "Septilin", salt: "Immunomodulator Herbal", category: "Generic Drugs", price: 150, mrp: 185, discount: 18, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Septilin" },
    { id: 97, name: "Solvin Cold", salt: "Chlorpheniramine & Phenylephrine", category: "Generic Drugs", price: 68, mrp: 85, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Solvin Cold" },
    { id: 85, name: "Sporlac DS", salt: "Lactic Acid Bacillus", category: "Generic Drugs", price: 110, mrp: 135, discount: 18, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Sporlac" },
    { id: 100, name: "Stemetil 5mg", salt: "Prochlorperazine Maleate", category: "Generic Drugs", price: 92, mrp: 115, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Stemetil" },
    { id: 11, name: "Taxim-O 200", salt: "Cefixime Trihydrate", category: "Antibiotics", price: 98, mrp: 115, discount: 14, imageUrl: "/productImage/Antibiotics.png", brandName: "Taxim-O" },
    { id: 19, name: "Telma 40", salt: "Telmisartan IP", category: "Cardiac Care", price: 82, mrp: 95, discount: 13, imageUrl: "/productImage/Cardiac_Care.png", brandName: "Telma" },
    { id: 31, name: "Teneligliptin 20", salt: "Teneligliptin Hydrobromide", category: "Diabetes Care", price: 88, mrp: 115, discount: 23, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Teneligliptin" },
    { id: 51, name: "Veenat 400", salt: "Imatinib", category: "Oncology Drugs", price: 2200, mrp: 2800, discount: 21, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Veenat" },
    { id: 7, name: "Vicks Action 500", salt: "Paracetamol, Phenylephrine", category: "Generic Drugs", price: 40, mrp: 50, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Vicks Action" },
    { id: 32, name: "Voglibose 0.3", salt: "Voglibose IP", category: "Diabetes Care", price: 75, mrp: 95, discount: 21, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Voglibose" },
    { id: 93, name: "Volini Gel", salt: "Diclofenac Diethylamine", category: "Generic Drugs", price: 155, mrp: 195, discount: 20, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Volini" },
    { id: 38, name: "Warf 5mg", salt: "Warfarin Sodium", category: "Life Saving Medicines", price: 120, mrp: 150, discount: 20, imageUrl: "/productImage/Life_Saving_Medicines.png", brandName: "Warf 5mg" },
    { id: 55, name: "Xeloda 500", salt: "Capecitabine", category: "Oncology Drugs", price: 1500, mrp: 1800, discount: 16, imageUrl: "/productImage/Oncology_Drugs.png", brandName: "Xeloda" },
    { id: 46, name: "Zentel Syrup", salt: "Albendazole Oral Suspension", category: "Pediatric Care", price: 28, mrp: 35, discount: 20, imageUrl: "/productImage/Pediatric_Care.png", brandName: "Zentel Syrup" },
    { id: 14, name: "Zifi 200", salt: "Cefixime", category: "Antibiotics", price: 92, mrp: 108, discount: 14, imageUrl: "/productImage/Antibiotics.png", brandName: "Zifi" },
    { id: 6, name: "Zincovit", salt: "Multivitamin & Minerals", category: "Generic Drugs", price: 95, mrp: 110, discount: 13, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Zincovit" },
    { id: 34, name: "Zita Met 50/500", salt: "Sitagliptin & Metformin", category: "Diabetes Care", price: 280, mrp: 320, discount: 12, imageUrl: "/productImage/Diabetes_Care.png", brandName: "Zita Met" },
    { id: 83, name: "Zyrtec 10mg", salt: "Cetirizine", category: "Generic Drugs", price: 18, mrp: 25, discount: 28, imageUrl: "/productImage/Generic_Drugs.png", brandName: "Zyrtec" }
];